### PR TITLE
chBenchmark: restore PthreadShim for macOS

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by benesch** [comment]
oh nvm 752c68ef3fe9780cc6afee96c956ce5fc2f2a880 😀

**Comment by jamii** [comment]
Sorry, I hit push in magit by habit and then remembered that we don't have push to master protection on chbenchmark.

**Comment by umanwizard** [comment]
@jamii Please feel free to use your discretion about whether to request reviews for this repo -- the consensus we came to here in NYC is that reviews are optional unless and until this becomes part of actual crucial production infrastructure.

**Comment by benesch** [comment]
Yeah, no worries at all! You didn't break protocol here :)

**Comment by benesch** [comment]
It's like the good old days!

**Pull request closed without merging**
